# -*- coding: utf-8 -*-
"""Automate_meta_nur_arfiya.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vicWj-pDNL0aZCaiQUm-iV8p3hx4v3PC
"""

import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler

print("=== Memulai Preprocessing Titanic Dataset ===")

# Load dataset raw
df = pd.read_csv("Titanic-Dataset.csv")

# Informasi awal
print("Jumlah data awal:", df.shape)

# Menghapus kolom yang tidak digunakan
df = df.drop(
    ['PassengerId', 'Name', 'Ticket', 'Cabin'],
    axis=1
)

# Menangani missing value
df['Age'] = df['Age'].fillna(
    df['Age'].median()
)

df['Embarked'] = df['Embarked'].fillna(
    df['Embarked'].mode()[0]
)

# Menghapus data duplikat
print("Jumlah duplikat:", df.duplicated().sum())

df = df.drop_duplicates()

print("Jumlah data setelah menghapus duplikat:", len(df))

# Encoding data kategorikal
encoder = LabelEncoder()

df['Sex'] = encoder.fit_transform(df['Sex'])
df['Embarked'] = encoder.fit_transform(df['Embarked'])

# Normalisasi fitur numerik
scaler = StandardScaler()

df[['Age', 'Fare']] = scaler.fit_transform(
    df[['Age', 'Fare']]
)

# Simpan hasil preprocessing
df.to_csv(
    "titanic_preprocessed.csv",
    index=False
)

print("Preprocessing selesai.")
print("Dataset berhasil disimpan sebagai titanic_preprocessed.csv")
print("Ukuran dataset akhir:", df.shape)